name: project_finder
description: Final Year Project - Thomas Turner

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  cloud_firestore: ^0.14.1+3
  google_fonts: ^1.1.2
  fluttertoast: ^7.1.6
  flutter_search_bar: ^2.1.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: any
  test: any
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/